# Generated by Django 3.0.8 on 2020-08-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='snippet',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='snippet_image',
            field=models.ImageField(blank=True, null=True, upload_to='snippet_pics'),
        ),
    ]
