# Generated by Django 3.0.8 on 2020-08-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200818_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='snippet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
