# Generated by Django 3.0.8 on 2020-08-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='email',
            new_name='subscribers',
        ),
    ]
