# Generated by Django 3.0.8 on 2020-08-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='email_pics',
            field=models.ImageField(blank=True, null=True, upload_to='email_pics'),
        ),
    ]
