# Generated by Django 3.0.8 on 2020-09-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_newsletter_email_pics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
