# Generated by Django 3.0.8 on 2020-09-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200908_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='snippet_img_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
