# Generated by Django 3.0.8 on 2021-01-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogpost_snippet_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='subscribers',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
